### ISSUE TITLE
Download for windows returns 404

### ISSUE THREAD

**Issue by MiKom** [git-lfs/git-lfs.github.com#17]
Points to: https://github.com/git-lfs/git-lfs/releases/download/v2.0.1/git-lfs-windows-2.0.1.exe

instead of: https://github.com/git-lfs/git-lfs/releases/download/v2.0.1/git-lfs-windows-2.0.1.ext.exe

(notice .ext.exe instad of .exe at the end)

**Comment by ttaylorr** [comment]
Hi @MiKom, thanks for opening this up. Taking a look at the website, we don't render `.ext` anywhere<sup>[[1](https://github.com/git-lfs/git-lfs.github.com/blob/b472bfd375e00c9a7104a23c8691f5f67de85674/_includes/home/secondary.html#L26)]</sup>:

```html
<a class="js-os-data" data-os-attr="href" data-ga-params="download,link"
   href="https://github.com/git-lfs/git-lfs/releases/latest"
   data-os-mac="https://github.com/git-lfs/git-lfs/releases/download/v{{site.git-lfs-release}}/git-lfs-darwin-amd64-{{site.git-lfs-release}}.tar.gz"
   data-os-windows="https://github.com/git-lfs/git-lfs/releases/download/v{{site.git-lfs-release}}/git-lfs-windows-{{site.git-lfs-release}}.exe"
   data-os-linux="https://github.com/git-lfs/git-lfs/releases/download/v{{site.git-lfs-release}}/git-lfs-linux-amd64-{{site.git-lfs-release}}.tar.gz">
   Download
</a>
```

Similarly, the filename of the Windows installer at 2.0.1 is `git-lfs-windows-2.0.1.exe`.

Is it possible that you have a user-script or some other browser extension that would be changing the contents of the page?

**Comment by technoweenie** [comment]
Ha, sorry I was a :trollface: I fixed the file extension, but forgot to update this issue :) It did in fact have an `ext` in the filename somewhere...
