### ISSUE TITLE
Spec URL points to invalid location

### ISSUE THREAD

**Issue by mlucool** [git-lfs/git-lfs.github.com#27]
I see the following invalid url from commands like git blame: https://git-lfs.github.com/spec/v1

Can this URL please be created? Per https://github.com/git-lfs/git-lfs/issues/2877#issuecomment-368702782 it seems the URL is intended to exist.

**Comment by ttaylorr** [comment]
Hi @mlucool, great idea, and thanks for picking this up over here. I made this the case in https://github.com/git-lfs/git-lfs.github.com/commit/929610a3819c813d3b9b4115bb6f9029eb2208f4.

From my terminal:

```
~/g/git-lfs.github.com (master) $ curl https://git-lfs.github.com/spec/v1 2>/dev/null | grep refresh
<meta http-equiv="refresh" content="0; url=https://git-lfs.github.com/">
```

If this change doesn't appear immediately for you, please wait for your DNS cache to flush.
