### ISSUE TITLE
update site to match README

### ISSUE THREAD

**Issue by srl295** [git-lfs/git-lfs.github.com#34]
Update `_includes/home/secondary.html` ? to address issues in https://github.com/git-lfs/git-lfs/issues/3181 and addressed in https://github.com/git-lfs/git-lfs/pull/3193 

in the **Getting Started** section,

- step 1 mentions to install the _binaries_, but `git lfs install` isn't an installer. (`install.sh` is)
- steps 2 and 3 ( git lfs track, git add, push etc) are _example usage_ and not part of the installation.

- It might be good to move step 1 of getting started up near the blue Download button, something such as "once downloaded, git lfs needs to be configured once…

Motivation: In [our instructions](http://site.icu-project.org/repository) for example, we are trying to refer to the git-lfs docs as a prereq to doing a `git clone`.  `git lfs track` for example is not needed before doing a `git clone` of an lfs-enabled repo.

**Comment by ttaylorr** [comment]
> Update `_includes/home/secondary.html` ? to address issues in
> https://github.com/git-lfs/git-lfs/issues/3181 and addressed in
> https://github.com/git-lfs/git-lfs/pull/3193

Sure, that sounds like a good approach to me. Let's close this issue and
turn those proposed changes into a pull request instead.

**Comment by srl295** [comment]
@ttaylorr I'm not going to be able to make a PR in the near future, so wanted to capture this. but however you want to handle.
