### ISSUE TITLE
Mention Git LFS program limitations on homepage

### ISSUE THREAD

**Issue by HonkingGoose** [git-lfs/git-lfs.github.com#48]
## Problem

It's impossible to find out what the limitations of the Git LFS program are from reading the homepage or the linked docs file.

## Current user journey

1. User learns that _Git LFS_ exists and uses "favorite search engine" to find out if it will work for their usecase.
2. User lands on the https://git-lfs.github.com/ homepage.
3. "_Git LFS_ might work for me, but what are the limitations? The homepage doesn't mention this at all..."
4. "Let's click on **Docs** in the navbar, maybe that will explain the limits of the program..."
5. User lands on https://github.com/git-lfs/git-lfs/tree/main/docs?utm_source=gitlfs_site&utm_medium=docs_link&utm_campaign=gitlfs "This file also doesn't mention limitations at all..."
6. User searches on the internet to try to find out what _Git LFS_ supports, and hopefully stumbles on https://github.com/git-lfs/git-lfs/wiki/Limitations somehow.
7. "Turns out I can use _Git LFS_, hooray!" or "Shame, Git LFS won't work for me!".
8. "That was a hassle finding out what the program supports!"

## Better user journey

1. User learns that _Git LFS_ exists and uses "favorite search engine" to find out if it will work for their usecase.
2. User lands on the https://git-lfs.github.com/ homepage.
3. "_Git LFS_ might work for me, but what are the limitations?"
4. "Oh, they have a link/section explaining the limits of the Git LFS program! Let's click on the link/read the section."
5. "_Git LFS_ will work for me!" or "_Git LFS_ won't work for me, I need to find an alternative".

### Option 1: Put link to `git-lfs` repo wiki on the homepage

Put a link to https://github.com/git-lfs/git-lfs/wiki/Limitations somewhere suitable on the homepage.

### Option 2: Make a new section: :"Known limitations" on the homepage.

I like this option better, as new users can see right away if Git LFS will work for them or not.

**Comment by chrisd8088** [comment]
Hey, thanks for the comments and proposals!  Personally, I think we would probably best be served with a link to the wiki on the home page, since that covers more ground in one simple change.

Also, it doesn't require keeping the home page up-to-date with every change to the server-side implementations of the LFS protocol by multiple vendors (GitHub, GitLab, etc.), which are outside of the control of this project and may change without warning to us (since the core Git LFS team only support the open-source client software).

**Comment by HonkingGoose** [comment]
> Hey, thanks for the comments and proposals!

You're welcome!

> Personally, I think we would probably best be served with a link to the wiki on the home page, since that covers more ground in one simple change.
>
> Also, it doesn't require keeping the home page up-to-date with every change to the server-side implementations of the LFS protocol by multiple vendors (GitHub, GitLab, etc.), which are outside of the control of this project and may change without warning to us (since the core Git LFS team only support the open-source client software).

Keeping up-to-date with upstream changes can be a lot of work, and it would mean you need to update the page frequently. Considering all this, a link to the wiki is probably easiest to maintain long term.
