### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by dphiffer** [git-lfs/git-lfs.github.com#9]
Loading https://git-lfs.github.com/ in a browser gives me a 404 error. Oddly, `curl -I https://git-lfs.github.com/` yields a 200 response.

Maybe this is just a temporary blip?

**Comment by technoweenie** [comment]
Possibly. I'm not seeing any issues now. Not sure what may have changed, as this page has been hosted on GH Pages since the beginning. Let me know if you're still experiencing problems.
